import { addDays, format } from "date-fns";
import type {
  Attraction,
  DayPlan,
  ExpenseItem,
  FoodItem,
  HotelBooking,
  JournalEntry,
  PackingItem,
  ScheduleItem,
  TransportLeg,
  TripSettings,
  WishlistItem,
} from "@/types";

export const DEFAULT_DEPARTURE = "2026-10-10";

function dayDate(offset: number, base: string = DEFAULT_DEPARTURE): string {
  return format(addDays(new Date(base + "T00:00:00"), offset), "yyyy-MM-dd");
}

export const defaultSettings: TripSettings = {
  tripTitle: "Japan Adventure 2026",
  departureDate: DEFAULT_DEPARTURE,
  returnDate: dayDate(14),
  icCardBalance: 8000,
  jrPassActive: true,
  jrPassExpiry: dayDate(9),
  walkingOverrideKm: null,
};

let scheduleIdCounter = 0;
let checklistIdCounter = 0;

function sched(
  time: string,
  title: string,
  category: ScheduleItem["category"],
  duration: string,
  notes = ""
): ScheduleItem {
  return {
    id: `sched-${scheduleIdCounter++}`,
    time,
    title,
    category,
    duration,
    notes,
    color:
      category === "food"
        ? "#E67E22"
        : category === "sight"
        ? "#E60026"
        : category === "transport"
        ? "#2C6EAA"
        : category === "shopping"
        ? "#8E44AD"
        : category === "rest"
        ? "#16A085"
        : "#7F8C8D",
  };
}

function checklist(items: string[]) {
  return items.map((text) => ({ id: `checklist-${checklistIdCounter++}`, text, done: false }));
}

interface DaySeed {
  title: string;
  city: DayPlan["city"];
  hotel: string;
  schedule: ScheduleItem[];
  notes: string;
  transportation: string;
  travelTime: string;
  walkingDistanceKm: number;
  budgetJPY: number;
  restaurants: string[];
  shopping: string[];
  images: string[];
  checklistItems: string[];
  mapQuery: string;
}

const raw: DaySeed[] = [
  {
    title: "Arrival in Tokyo",
    city: "Tokyo",
    hotel: "Shinjuku Granbell Hotel",
    schedule: [
      sched("14:00", "Land at Haneda / Narita", "transport", "1h", "Immigration + baggage claim"),
      sched("16:00", "Airport Limousine Bus to Shinjuku", "transport", "1h30"),
      sched("18:00", "Hotel check-in", "rest", "30m"),
      sched("19:30", "Evening walk — Omoide Yokocho", "sight", "1h"),
      sched("20:30", "Ramen dinner", "food", "1h", "Fuunji or Ichiran"),
    ],
    notes: "Land, breathe, and get the first taste of Tokyo neon before crashing the jet lag off.",
    transportation: "Airport Limousine Bus",
    travelTime: "1h 30m",
    walkingDistanceKm: 3.2,
    budgetJPY: 12000,
    restaurants: ["Ichiran Shinjuku", "Omoide Yokocho stalls"],
    shopping: ["Don Quijote Shinjuku"],
    images: [],
    checklistItems: ["Exchange some cash", "Get pocket wifi / SIM", "Set up IC card"],
    mapQuery: "Shinjuku Station, Tokyo",
  },
  {
    title: "Tokyo First Impressions",
    city: "Tokyo",
    hotel: "Shinjuku Granbell Hotel",
    schedule: [
      sched("08:00", "Breakfast at hotel", "food", "45m"),
      sched("09:30", "Meiji Jingu Shrine", "sight", "1h30"),
      sched("11:30", "Harajuku Takeshita Street", "shopping", "1h30"),
      sched("13:30", "Lunch — Harajuku crepes & gyoza", "food", "1h"),
      sched("15:00", "Shibuya Crossing & Sky", "sight", "2h"),
      sched("18:00", "Sunset at Shibuya Sky", "sight", "1h"),
      sched("20:00", "Izakaya dinner", "food", "1h30"),
    ],
    notes: "Classic Tokyo trifecta: shrine calm, Harajuku chaos, Shibuya lights.",
    transportation: "JR Yamanote Line",
    travelTime: "20m",
    walkingDistanceKm: 8.5,
    budgetJPY: 15000,
    restaurants: ["Uobei Shibuya (conveyor sushi)", "Local izakaya near Nonbei Yokocho"],
    shopping: ["Takeshita Street", "Shibuya 109"],
    images: [],
    checklistItems: ["Book Shibuya Sky ticket in advance", "Charge camera battery"],
    mapQuery: "Shibuya Crossing, Tokyo",
  },
  {
    title: "Travel to Kyoto",
    city: "Kyoto",
    hotel: "Kyoto Granbell Hotel Gion",
    schedule: [
      sched("08:00", "Breakfast & check out", "food", "45m"),
      sched("09:30", "Shinkansen Tokyo → Kyoto", "transport", "2h20", "Nozomi/Hikari, reserved seats"),
      sched("12:30", "Lunch near Kyoto Station", "food", "1h"),
      sched("14:00", "Hotel check-in, Gion", "rest", "30m"),
      sched("15:00", "Gion district stroll", "sight", "2h"),
      sched("18:00", "Kaiseki dinner", "food", "2h"),
      sched("20:30", "Maiko spotting on Hanamikoji", "sight", "45m"),
    ],
    notes: "The bullet train ride itself is a highlight — grab a window seat for Fuji views.",
    transportation: "Tokaido Shinkansen",
    travelTime: "2h 20m",
    walkingDistanceKm: 5.4,
    budgetJPY: 20000,
    restaurants: ["Gion Karyo (kaiseki)", "Kyoto Station ramen alley"],
    shopping: ["Hanamikoji street shops"],
    images: [],
    checklistItems: ["Reserve Shinkansen seats", "Store luggage forward if needed"],
    mapQuery: "Gion, Kyoto",
  },
  {
    title: "Fushimi Inari & Kiyomizu",
    city: "Kyoto",
    hotel: "Kyoto Granbell Hotel Gion",
    schedule: [
      sched("07:30", "Early breakfast", "food", "30m"),
      sched("08:00", "Fushimi Inari Taisha", "sight", "2h30", "Beat the crowds, hike the torii gates"),
      sched("11:00", "Coffee break", "food", "30m"),
      sched("13:00", "Lunch — Nishiki Market snacking", "food", "1h30"),
      sched("15:00", "Kiyomizu-dera Temple", "sight", "1h30"),
      sched("17:00", "Higashiyama district shopping", "shopping", "1h"),
      sched("19:00", "Dinner in Pontocho Alley", "food", "1h30"),
    ],
    notes: "Two of Kyoto's most iconic sights back to back — comfortable shoes essential.",
    transportation: "JR Nara Line + walking",
    travelTime: "35m",
    walkingDistanceKm: 12.1,
    budgetJPY: 9000,
    restaurants: ["Nishiki Market stalls", "Pontocho Alley riverside dining"],
    shopping: ["Sannenzaka & Ninenzaka lanes"],
    images: [],
    checklistItems: ["Bring good walking shoes", "Carry cash for market stalls"],
    mapQuery: "Fushimi Inari Taisha, Kyoto",
  },
  {
    title: "Arashiyama & Kinkaku-ji",
    city: "Kyoto",
    hotel: "Kyoto Granbell Hotel Gion",
    schedule: [
      sched("08:00", "Breakfast", "food", "45m"),
      sched("09:30", "Arashiyama Bamboo Grove", "sight", "1h"),
      sched("11:00", "Tenryu-ji Temple garden", "sight", "1h"),
      sched("13:00", "Lunch — Yudofu tofu kaiseki", "food", "1h"),
      sched("15:00", "Kinkaku-ji Golden Pavilion", "sight", "1h30"),
      sched("17:30", "Nijo Castle grounds", "sight", "1h"),
      sched("19:30", "Dinner — Kyoto-style obanzai", "food", "1h30"),
    ],
    notes: "A full day of gardens and gold — go early to Arashiyama before tour buses arrive.",
    transportation: "JR Sagano Line + City Bus",
    travelTime: "45m",
    walkingDistanceKm: 10.3,
    budgetJPY: 11000,
    restaurants: ["Arashiyama Yoshida-ya (yudofu)", "Obanzai izakaya in Gion"],
    shopping: ["Arashiyama souvenir street"],
    images: [],
    checklistItems: ["Buy one-day bus pass", "Check Kinkaku-ji closing time"],
    mapQuery: "Arashiyama Bamboo Grove, Kyoto",
  },
  {
    title: "Travel to Osaka",
    city: "Osaka",
    hotel: "Osaka Marriott Miyako Hotel",
    schedule: [
      sched("09:00", "Check out, Nishiki Market last stop", "shopping", "1h"),
      sched("11:00", "JR Special Rapid to Osaka", "transport", "30m"),
      sched("12:00", "Hotel check-in", "rest", "30m"),
      sched("13:00", "Lunch in Namba", "food", "1h"),
      sched("15:00", "Dotonbori canal walk", "sight", "2h"),
      sched("18:00", "Sunset photos — Glico sign", "sight", "30m"),
      sched("20:00", "Street food crawl", "food", "2h"),
    ],
    notes: "Short scenic train ride into Japan's kitchen — arrive hungry.",
    transportation: "JR Kyoto Line (Special Rapid)",
    travelTime: "30m",
    walkingDistanceKm: 9.0,
    budgetJPY: 14000,
    restaurants: ["Dotonbori takoyaki stalls", "Kani Doraku crab restaurant"],
    shopping: ["Shinsaibashi-suji shopping arcade"],
    images: [],
    checklistItems: ["Try takoyaki fresh off the griddle"],
    mapQuery: "Dotonbori, Osaka",
  },
  {
    title: "Osaka Castle & Universal Studios",
    city: "Osaka",
    hotel: "Osaka Marriott Miyako Hotel",
    schedule: [
      sched("08:00", "Breakfast", "food", "30m"),
      sched("09:00", "Osaka Castle & park", "sight", "2h"),
      sched("12:00", "Lunch near castle park", "food", "1h"),
      sched("14:00", "Universal Studios Japan", "sight", "6h", "Super Nintendo World"),
      sched("20:30", "Dinner near Universal CityWalk", "food", "1h"),
    ],
    notes: "Theme park day — consider an Express Pass to skip lines at Super Nintendo World.",
    transportation: "Osaka Loop Line + JR Yumesaki Line",
    travelTime: "40m",
    walkingDistanceKm: 11.6,
    budgetJPY: 25000,
    restaurants: ["CityWalk food court", "Universal Harbor restaurants"],
    shopping: ["Universal Studios Store"],
    images: [],
    checklistItems: ["Buy USJ tickets online in advance", "Download Universal app"],
    mapQuery: "Universal Studios Japan, Osaka",
  },
  {
    title: "Nara Day Trip",
    city: "Osaka",
    hotel: "Osaka Marriott Miyako Hotel",
    schedule: [
      sched("08:00", "Breakfast", "food", "30m"),
      sched("09:00", "Kintetsu train to Nara", "transport", "40m"),
      sched("10:00", "Nara Park — deer feeding", "sight", "2h"),
      sched("12:30", "Todai-ji Temple, Great Buddha Hall", "sight", "1h30"),
      sched("14:30", "Lunch in Naramachi", "food", "1h"),
      sched("16:00", "Return to Osaka", "transport", "40m"),
      sched("18:00", "Kuromon Ichiba Market dinner crawl", "food", "2h"),
    ],
    notes: "A half-day escape to friendly deer and one of Japan's oldest wooden buildings.",
    transportation: "Kintetsu Nara Line",
    travelTime: "40m",
    walkingDistanceKm: 9.8,
    budgetJPY: 8000,
    restaurants: ["Naramachi tea houses", "Kuromon Ichiba Market stalls"],
    shopping: ["Kuromon Ichiba Market"],
    images: [],
    checklistItems: ["Buy deer crackers", "Watch belongings around deer"],
    mapQuery: "Nara Park, Nara",
  },
  {
    title: "Travel to Tokyo",
    city: "Tokyo",
    hotel: "Park Hotel Tokyo",
    schedule: [
      sched("09:00", "Check out", "rest", "30m"),
      sched("10:00", "Shinkansen Osaka → Tokyo", "transport", "2h30", "Nozomi, reserved seats"),
      sched("13:00", "Lunch at Tokyo Station", "food", "1h"),
      sched("15:00", "Hotel check-in, Shiodome", "rest", "30m"),
      sched("16:30", "Hamarikyu Gardens", "sight", "1h30"),
      sched("19:00", "Dinner in Shimbashi", "food", "1h30"),
    ],
    notes: "Back to the capital for the second half of the trip.",
    transportation: "Tokaido Shinkansen",
    travelTime: "2h 30m",
    walkingDistanceKm: 6.2,
    budgetJPY: 18000,
    restaurants: ["Tokyo Station Ramen Street", "Shimbashi salaryman izakayas"],
    shopping: ["Tokyo Character Street"],
    images: [],
    checklistItems: ["Reserve return Shinkansen seats"],
    mapQuery: "Shiodome, Tokyo",
  },
  {
    title: "Asakusa & Akihabara",
    city: "Tokyo",
    hotel: "Park Hotel Tokyo",
    schedule: [
      sched("08:00", "Breakfast", "food", "45m"),
      sched("09:30", "Senso-ji Temple & Nakamise Street", "sight", "2h"),
      sched("12:00", "Lunch — tempura in Asakusa", "food", "1h"),
      sched("14:00", "Tokyo Skytree observation deck", "sight", "1h30"),
      sched("16:00", "Akihabara electronics & anime district", "shopping", "2h30"),
      sched("19:00", "Themed café dinner", "food", "1h30"),
    ],
    notes: "Old Tokyo in the morning, futuristic Tokyo by afternoon.",
    transportation: "Tokyo Metro Ginza Line",
    travelTime: "25m",
    walkingDistanceKm: 10.7,
    budgetJPY: 16000,
    restaurants: ["Asakusa tempura counters", "Akihabara themed cafés"],
    shopping: ["Nakamise shopping street", "Akihabara Radio Kaikan"],
    images: [],
    checklistItems: ["Pre-book Skytree tickets"],
    mapQuery: "Senso-ji Temple, Tokyo",
  },
  {
    title: "teamLab & Odaiba",
    city: "Tokyo",
    hotel: "Park Hotel Tokyo",
    schedule: [
      sched("09:00", "Breakfast", "food", "45m"),
      sched("11:00", "teamLab Planets / Borderless", "sight", "2h30", "Book timed entry"),
      sched("14:00", "Lunch in Odaiba", "food", "1h"),
      sched("15:30", "Odaiba waterfront & Gundam statue", "sight", "2h"),
      sched("18:00", "Sunset over Rainbow Bridge", "sight", "45m"),
      sched("19:30", "Dinner — Odaiba mall food court", "food", "1h30"),
    ],
    notes: "Digital art immersion followed by a futuristic waterfront evening.",
    transportation: "Yurikamome Line",
    travelTime: "30m",
    walkingDistanceKm: 9.4,
    budgetJPY: 14000,
    restaurants: ["DiverCity Tokyo Plaza food court"],
    shopping: ["DiverCity Tokyo Plaza"],
    images: [],
    checklistItems: ["Book teamLab timed tickets", "Charge phone for photos"],
    mapQuery: "teamLab Planets, Tokyo",
  },
  {
    title: "Shinjuku & Shopping Day",
    city: "Tokyo",
    hotel: "Park Hotel Tokyo",
    schedule: [
      sched("08:30", "Breakfast", "food", "45m"),
      sched("10:00", "Shinjuku Gyoen National Garden", "sight", "1h30"),
      sched("12:00", "Lunch — soba noodles", "food", "1h"),
      sched("13:30", "Ginza shopping district", "shopping", "3h"),
      sched("17:00", "Coffee break", "food", "30m"),
      sched("18:30", "Tokyo Tower at dusk", "sight", "1h"),
      sched("20:00", "Dinner — yakitori alley", "food", "1h30"),
    ],
    notes: "A gentler day mixing gardens with flagship shopping.",
    transportation: "Tokyo Metro Marunouchi Line",
    travelTime: "25m",
    walkingDistanceKm: 8.8,
    budgetJPY: 22000,
    restaurants: ["Ginza soba house", "Yakitori alley near Yurakucho"],
    shopping: ["Ginza Six", "Uniqlo flagship Ginza"],
    images: [],
    checklistItems: ["Leave room in luggage for souvenirs"],
    mapQuery: "Ginza, Tokyo",
  },
  {
    title: "Free Day — Disney or Ghibli",
    city: "Tokyo",
    hotel: "Park Hotel Tokyo",
    schedule: [
      sched("08:00", "Breakfast", "food", "45m"),
      sched("09:30", "Tokyo Disneyland / DisneySea", "sight", "8h", "Or Ghibli Museum + Kichijoji"),
      sched("19:00", "Dinner near hotel", "food", "1h30"),
      sched("21:00", "Pack souvenirs", "rest", "1h"),
    ],
    notes: "Flex day — swap in Ghibli Museum, Kamakura day trip, or simply rest.",
    transportation: "JR / Disney Resort Line",
    travelTime: "45m",
    walkingDistanceKm: 7.5,
    budgetJPY: 20000,
    restaurants: ["Park resort dining"],
    shopping: ["Disney / Ghibli merchandise"],
    images: [],
    checklistItems: ["Book Disney tickets in advance", "Start packing"],
    mapQuery: "Tokyo Disneyland",
  },
  {
    title: "Last Tokyo Day",
    city: "Tokyo",
    hotel: "Park Hotel Tokyo",
    schedule: [
      sched("08:00", "Breakfast", "food", "45m"),
      sched("09:30", "Last-minute souvenir shopping", "shopping", "2h"),
      sched("12:00", "Farewell sushi lunch", "food", "1h30", "Tsukiji Outer Market"),
      sched("14:00", "Return to hotel, finish packing", "rest", "1h30"),
      sched("16:00", "Relax — onsen or spa", "rest", "2h"),
      sched("19:00", "Farewell dinner", "food", "2h", "Treat yourself"),
    ],
    notes: "Savor the last full day — leave time to repack and weigh luggage.",
    transportation: "Tokyo Metro",
    travelTime: "20m",
    walkingDistanceKm: 6.0,
    budgetJPY: 20000,
    restaurants: ["Tsukiji Outer Market sushi counters", "Farewell dinner splurge spot"],
    shopping: ["Tsukiji Outer Market", "Last souvenir run"],
    images: [],
    checklistItems: ["Weigh luggage", "Confirm airport transfer time"],
    mapQuery: "Tsukiji Outer Market, Tokyo",
  },
  {
    title: "Departure",
    city: "Tokyo",
    hotel: "—",
    schedule: [
      sched("07:00", "Final breakfast", "food", "45m"),
      sched("08:00", "Check out", "rest", "30m"),
      sched("09:00", "Airport Limousine Bus to airport", "transport", "1h30"),
      sched("11:30", "Check-in & duty free", "shopping", "1h"),
      sched("14:00", "Flight departs", "transport", "—", "Sayonara, Japan"),
    ],
    notes: "Bittersweet last morning — leave extra buffer time for airport traffic.",
    transportation: "Airport Limousine Bus",
    travelTime: "1h 30m",
    walkingDistanceKm: 2.0,
    budgetJPY: 6000,
    restaurants: ["Airport dining"],
    shopping: ["Airport duty free"],
    images: [],
    checklistItems: ["Passport & boarding pass ready", "Declare nothing forbidden", "Say goodbye to Japan"],
    mapQuery: "Haneda Airport, Tokyo",
  },
];

export function buildInitialDays(base: string = DEFAULT_DEPARTURE): DayPlan[] {
  return raw.map((d, i) => ({
    id: `day-${i + 1}`,
    dayNumber: i + 1,
    date: dayDate(i, base),
    title: d.title,
    city: d.city,
    hotel: d.hotel,
    weather: { icon: "⛅", tempHigh: 22, tempLow: 14, condition: "Partly cloudy" },
    walkingDistanceKm: d.walkingDistanceKm,
    budgetJPY: d.budgetJPY,
    notes: d.notes,
    hiddenNotes: "",
    priority: i === 3 || i === 6 || i === 10 ? "high" : "medium",
    checklist: checklist(d.checklistItems),
    images: d.images,
    transportation: d.transportation,
    travelTime: d.travelTime,
    schedule: d.schedule,
    restaurants: d.restaurants,
    shopping: d.shopping,
    mapQuery: d.mapQuery,
  }));
}

export const initialAttractions: Attraction[] = ([
  {
    id: "", name: "Fushimi Inari Taisha", city: "Kyoto", emoji: "⛩️",
    image: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?q=80&w=1200&auto=format&fit=crop",
    description: "Thousands of vermilion torii gates winding up Mount Inari.",
    rating: 4.8, visitDuration: "2-3 hours", openingHours: "24 hours", cost: "Free",
    nearbyRestaurants: ["Vermillion Cafe", "Inari sushi stalls"], nearbyCafes: ["Vermillion Cafe"],
    nearestStation: "Inari Station (JR Nara Line)", website: "https://inari.jp/en/",
    notes: "", visited: false, favorite: true, lat: 34.9671, lng: 135.7727,
  },
  {
    id: "", name: "Kiyomizu-dera", city: "Kyoto", emoji: "🏯",
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?q=80&w=1200&auto=format&fit=crop",
    description: "Historic wooden temple with a sweeping city-view veranda.",
    rating: 4.7, visitDuration: "1.5 hours", openingHours: "6:00–18:00", cost: "¥400",
    nearbyRestaurants: ["Yasaka Dori restaurants"], nearbyCafes: ["%Arabica Kiyomizu"],
    nearestStation: "Kiyomizu-Gojo Station", website: "https://www.kiyomizudera.or.jp/en/",
    notes: "", visited: false, favorite: false, lat: 34.9948, lng: 135.785,
  },
  {
    id: "", name: "Arashiyama Bamboo Grove", city: "Kyoto", emoji: "🎍",
    image: "https://images.unsplash.com/photo-1503149779833-1de50ebe5f8a?q=80&w=1200&auto=format&fit=crop",
    description: "Towering bamboo stalks lining a serene walking path.",
    rating: 4.6, visitDuration: "1 hour", openingHours: "24 hours", cost: "Free",
    nearbyRestaurants: ["Arashiyama Yoshida-ya"], nearbyCafes: ["%Arabica Arashiyama"],
    nearestStation: "Saga-Arashiyama Station", website: "https://www.kyokanko.or.jp/arashiyama/",
    notes: "", visited: false, favorite: false, lat: 35.0094, lng: 135.6667,
  },
  {
    id: "", name: "Kinkaku-ji (Golden Pavilion)", city: "Kyoto", emoji: "🌟",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?q=80&w=1200&auto=format&fit=crop",
    description: "Gold-leaf-covered pavilion reflecting over a still pond.",
    rating: 4.7, visitDuration: "1 hour", openingHours: "9:00–17:00", cost: "¥500",
    nearbyRestaurants: ["Local soba shops"], nearbyCafes: ["Kinkaku-ji tea house"],
    nearestStation: "Kinkakuji-michi bus stop", website: "https://www.shokoku-ji.jp/en/kinkakuji/",
    notes: "", visited: false, favorite: true, lat: 35.0394, lng: 135.7292,
  },
  {
    id: "", name: "Nijo Castle", city: "Kyoto", emoji: "🏰",
    image: "https://images.unsplash.com/photo-1624253321171-1be53e12f5f4?q=80&w=1200&auto=format&fit=crop",
    description: "Shogun-era castle famous for its 'nightingale' chirping floors.",
    rating: 4.5, visitDuration: "1.5 hours", openingHours: "8:45–16:00", cost: "¥1,300",
    nearbyRestaurants: ["Nijo-jo-mae eateries"], nearbyCafes: ["Nearby matcha cafes"],
    nearestStation: "Nijojo-mae Station", website: "https://nijo-jocastle.city.kyoto.lg.jp/en/",
    notes: "", visited: false, favorite: false, lat: 35.0141, lng: 135.748,
  },
  {
    id: "", name: "Osaka Castle", city: "Osaka", emoji: "🏯",
    image: "https://images.unsplash.com/photo-1590559899731-a382839e5549?q=80&w=1200&auto=format&fit=crop",
    description: "Iconic castle tower surrounded by moats and a spacious park.",
    rating: 4.6, visitDuration: "2 hours", openingHours: "9:00–17:00", cost: "¥600",
    nearbyRestaurants: ["Castle park food stalls"], nearbyCafes: ["JO-TERRACE Osaka cafes"],
    nearestStation: "Osakajokoen Station", website: "https://www.osakacastle.net/",
    notes: "", visited: false, favorite: false, lat: 34.6873, lng: 135.5262,
  },
  {
    id: "", name: "Dotonbori", city: "Osaka", emoji: "🍢",
    image: "https://images.unsplash.com/photo-1590251857349-a5629f19be1e?q=80&w=1200&auto=format&fit=crop",
    description: "Neon-lit canal district famous for street food and the Glico sign.",
    rating: 4.7, visitDuration: "2-3 hours", openingHours: "24 hours", cost: "Free to walk",
    nearbyRestaurants: ["Kinryu Ramen", "Kani Doraku"], nearbyCafes: ["Streetside cafes"],
    nearestStation: "Namba Station", website: "https://dotonbori.or.jp/en/",
    notes: "", visited: false, favorite: true, lat: 34.6687, lng: 135.503,
  },
  {
    id: "", name: "Universal Studios Japan", city: "Osaka", emoji: "🎢",
    image: "https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?q=80&w=1200&auto=format&fit=crop",
    description: "Theme park with Super Nintendo World and Wizarding World of Harry Potter.",
    rating: 4.6, visitDuration: "Full day", openingHours: "9:00–20:00", cost: "¥8,600+",
    nearbyRestaurants: ["CityWalk restaurants"], nearbyCafes: ["Park cafes"],
    nearestStation: "Universal City Station", website: "https://www.usj.co.jp/e/",
    notes: "", visited: false, favorite: true, lat: 34.6654, lng: 135.4323,
  },
  {
    id: "", name: "Nara Park & Todai-ji", city: "Osaka", emoji: "🦌",
    image: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?q=80&w=1200&auto=format&fit=crop",
    description: "Free-roaming deer and the Great Buddha Hall, the world's largest wooden building.",
    rating: 4.7, visitDuration: "3 hours", openingHours: "7:30–17:30", cost: "¥800",
    nearbyRestaurants: ["Naramachi tea houses"], nearbyCafes: ["Nakatanidou mochi shop"],
    nearestStation: "Kintetsu Nara Station", website: "https://www.todaiji.or.jp/en/",
    notes: "", visited: false, favorite: false, lat: 34.6851, lng: 135.8048,
  },
  {
    id: "", name: "Shibuya Crossing & Sky", city: "Tokyo", emoji: "🚦",
    image: "https://images.unsplash.com/photo-1554797589-7241bb691973?q=80&w=1200&auto=format&fit=crop",
    description: "The world's busiest pedestrian scramble, viewed from above at Shibuya Sky.",
    rating: 4.6, visitDuration: "2 hours", openingHours: "10:00–22:30", cost: "¥2,000",
    nearbyRestaurants: ["Uobei Shibuya"], nearbyCafes: ["Streamer Coffee Company"],
    nearestStation: "Shibuya Station", website: "https://www.shibuya-scramble-square.com/sky/",
    notes: "", visited: false, favorite: true, lat: 35.6595, lng: 139.7005,
  },
  {
    id: "", name: "Senso-ji Temple", city: "Tokyo", emoji: "🎐",
    image: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?q=80&w=1200&auto=format&fit=crop",
    description: "Tokyo's oldest temple with the iconic Kaminarimon thunder gate.",
    rating: 4.6, visitDuration: "1.5 hours", openingHours: "6:00–17:00", cost: "Free",
    nearbyRestaurants: ["Nakamise Street snacks"], nearbyCafes: ["Asakusa tea houses"],
    nearestStation: "Asakusa Station", website: "https://www.senso-ji.jp/",
    notes: "", visited: false, favorite: false, lat: 35.7148, lng: 139.7967,
  },
  {
    id: "", name: "teamLab Planets", city: "Tokyo", emoji: "🌌",
    image: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?q=80&w=1200&auto=format&fit=crop",
    description: "Immersive digital art installations you walk barefoot through water.",
    rating: 4.8, visitDuration: "2.5 hours", openingHours: "9:00–21:00", cost: "¥3,800",
    nearbyRestaurants: ["Toyosu Market sushi"], nearbyCafes: ["Toyosu cafes"],
    nearestStation: "Shin-Toyosu Station", website: "https://www.teamlab.art/e/planets/",
    notes: "", visited: false, favorite: true, lat: 35.6469, lng: 139.7928,
  },
  {
    id: "", name: "Tokyo Skytree", city: "Tokyo", emoji: "🗼",
    image: "https://images.unsplash.com/photo-1601823984263-b87b59798b70?q=80&w=1200&auto=format&fit=crop",
    description: "Tallest structure in Japan with panoramic observation decks.",
    rating: 4.5, visitDuration: "1.5 hours", openingHours: "10:00–21:00", cost: "¥2,100+",
    nearbyRestaurants: ["Solamachi mall dining"], nearbyCafes: ["Skytree cafes"],
    nearestStation: "Tokyo Skytree Station", website: "https://www.tokyo-skytree.jp/en/",
    notes: "", visited: false, favorite: false, lat: 35.7101, lng: 139.8107,
  },
  {
    id: "", name: "Shinjuku Gyoen", city: "Tokyo", emoji: "🌸",
    image: "https://images.unsplash.com/photo-1522383225653-ed111181a951?q=80&w=1200&auto=format&fit=crop",
    description: "Sprawling park blending Japanese, French, and English garden styles.",
    rating: 4.7, visitDuration: "1.5 hours", openingHours: "9:00–16:30", cost: "¥500",
    nearbyRestaurants: ["Shinjuku soba shops"], nearbyCafes: ["Park-side cafes"],
    nearestStation: "Shinjuku-gyoenmae Station", website: "https://www.env.go.jp/garden/shinjukugyoen/",
    notes: "", visited: false, favorite: false, lat: 35.6852, lng: 139.71,
  },
  {
    id: "", name: "Ginza District", city: "Tokyo", emoji: "🛍️",
    image: "https://images.unsplash.com/photo-1533050487297-09b450131914?q=80&w=1200&auto=format&fit=crop",
    description: "Tokyo's flagship shopping and dining district.",
    rating: 4.5, visitDuration: "2-3 hours", openingHours: "10:00–20:00", cost: "Free to walk",
    nearbyRestaurants: ["Ginza soba house", "Sushi counters"], nearbyCafes: ["Ginza Six cafes"],
    nearestStation: "Ginza Station", website: "https://www.ginza.jp/en",
    notes: "", visited: false, favorite: false, lat: 35.6717, lng: 139.7648,
  },
] satisfies Attraction[]).map((a, i) => ({ ...a, id: `attraction-${i}` }));

export const initialHotels: HotelBooking[] = ([
  {
    id: "", city: "Tokyo", name: "Shinjuku Granbell Hotel",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1200&auto=format&fit=crop",
    address: "2-14-5 Kabukicho, Shinjuku, Tokyo",
    checkIn: dayDate(0), checkOut: dayDate(2),
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Shinjuku+Granbell+Hotel",
    confirmation: "CONF-TK-0001", notes: "Requested high floor, city view.",
  },
  {
    id: "", city: "Kyoto", name: "Kyoto Granbell Hotel Gion",
    image: "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?q=80&w=1200&auto=format&fit=crop",
    address: "570-127 Gionmachi Minamigawa, Higashiyama, Kyoto",
    checkIn: dayDate(2), checkOut: dayDate(5),
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Kyoto+Granbell+Hotel+Gion",
    confirmation: "CONF-KY-0002", notes: "Walking distance to Gion district.",
  },
  {
    id: "", city: "Osaka", name: "Osaka Marriott Miyako Hotel",
    image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?q=80&w=1200&auto=format&fit=crop",
    address: "1-1-43 Abenosuji, Abeno-ku, Osaka",
    checkIn: dayDate(5), checkOut: dayDate(8),
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Osaka+Marriott+Miyako+Hotel",
    confirmation: "CONF-OS-0003", notes: "Directly connected to Tennoji Station.",
  },
  {
    id: "", city: "Tokyo", name: "Park Hotel Tokyo",
    image: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=1200&auto=format&fit=crop",
    address: "1-7-1 Higashi-Shimbashi, Minato, Tokyo",
    checkIn: dayDate(8), checkOut: dayDate(14),
    mapsUrl: "https://www.google.com/maps/search/?api=1&query=Park+Hotel+Tokyo",
    confirmation: "CONF-TK-0004", notes: "Artist rooms — ask for a themed floor.",
  },
] satisfies HotelBooking[]).map((h, i) => ({ ...h, id: `hotel-${i}` }));

export const initialExpenses: ExpenseItem[] = ([
  { id: "", category: "Flights", description: "Round-trip international flights", amountJPY: 280000, date: dayDate(0), paid: true },
  { id: "", category: "Hotels", description: "Shinjuku Granbell Hotel (2 nights)", amountJPY: 46000, date: dayDate(0), paid: true },
  { id: "", category: "Hotels", description: "Kyoto Granbell Hotel Gion (3 nights)", amountJPY: 63000, date: dayDate(2), paid: true },
  { id: "", category: "Hotels", description: "Osaka Marriott Miyako (3 nights)", amountJPY: 72000, date: dayDate(5), paid: true },
  { id: "", category: "Hotels", description: "Park Hotel Tokyo (6 nights)", amountJPY: 138000, date: dayDate(8), paid: true },
  { id: "", category: "Transportation", description: "7-day JR Pass", amountJPY: 50000, date: dayDate(0), paid: true },
  { id: "", category: "Transportation", description: "IC Card top-up", amountJPY: 8000, date: dayDate(0), paid: false },
  { id: "", category: "Entertainment", description: "Universal Studios Japan ticket", amountJPY: 9400, date: dayDate(6), paid: false },
  { id: "", category: "Entertainment", description: "teamLab Planets ticket", amountJPY: 3800, date: dayDate(11), paid: false },
  { id: "", category: "Food", description: "Estimated meals budget", amountJPY: 90000, date: dayDate(0), paid: false },
  { id: "", category: "Shopping", description: "Souvenir budget", amountJPY: 40000, date: dayDate(0), paid: false },
  { id: "", category: "Miscellaneous", description: "Travel insurance", amountJPY: 12000, date: dayDate(0), paid: true },
] satisfies ExpenseItem[]).map((e, i) => ({ ...e, id: `expense-${i}` }));

export const initialPacking: PackingItem[] = [
  { id: "", text: "Passport", packed: false, category: "Documents" },
  { id: "", text: "JR Pass exchange voucher", packed: false, category: "Documents" },
  { id: "", text: "Travel insurance printout", packed: false, category: "Documents" },
  { id: "", text: "Hotel booking confirmations", packed: false, category: "Documents" },
  { id: "", text: "Power bank", packed: false, category: "Electronics" },
  { id: "", text: "Camera", packed: false, category: "Electronics" },
  { id: "", text: "Chargers & cables", packed: false, category: "Electronics" },
  { id: "", text: "SIM card / pocket wifi", packed: false, category: "Electronics" },
  { id: "", text: "Universal plug adapter", packed: false, category: "Electronics" },
  { id: "", text: "Medicine & first-aid kit", packed: false, category: "Health" },
  { id: "", text: "Comfortable walking shoes", packed: false, category: "Clothes" },
  { id: "", text: "Clothes for 15 days", packed: false, category: "Clothes" },
  { id: "", text: "Light jacket", packed: false, category: "Clothes" },
  { id: "", text: "Umbrella", packed: false, category: "Clothes" },
  { id: "", text: "Toiletries", packed: false, category: "Health" },
].map((p, i) => ({ ...p, id: `packing-${i}` }));

export const initialFood: FoodItem[] = [
  { id: "", name: "Sushi", emoji: "🍣", description: "Fresh nigiri and sashimi at a proper sushi-ya.", tried: false },
  { id: "", name: "Ramen", emoji: "🍜", description: "Rich tonkotsu or shoyu broth noodles.", tried: false },
  { id: "", name: "Curry", emoji: "🍛", description: "Japanese-style curry rice.", tried: false },
  { id: "", name: "Gyoza", emoji: "🥟", description: "Pan-fried dumplings.", tried: false },
  { id: "", name: "Dango", emoji: "🍡", description: "Sweet rice dumpling skewers.", tried: false },
  { id: "", name: "Wagyu", emoji: "🥩", description: "Melt-in-your-mouth premium beef.", tried: false },
  { id: "", name: "Japanese Cheesecake", emoji: "🍰", description: "Fluffy, jiggly cotton cheesecake.", tried: false },
  { id: "", name: "Onigiri", emoji: "🍙", description: "Rice balls from a konbini or a proper shop.", tried: false },
  { id: "", name: "Yakitori", emoji: "🍢", description: "Grilled skewers under a train bridge.", tried: false },
  { id: "", name: "Matcha Desserts", emoji: "🍵", description: "Matcha parfait, ice cream, or soft serve.", tried: false },
].map((f, i) => ({ ...f, id: `food-${i}` }));

export const initialWishlist: WishlistItem[] = ([
  { id: "", name: "Ghibli Museum", city: "Tokyo", priority: "high", favorite: true, notes: "Timed tickets sell out fast — book early." },
  { id: "", name: "Kamakura day trip", city: "Tokyo", priority: "medium", favorite: false, notes: "Great Buddha + coastal views." },
  { id: "", name: "Nintendo Museum", city: "Kyoto", priority: "medium", favorite: false, notes: "Reservation via lottery system." },
  { id: "", name: "Owl / Hedgehog Café", city: "Tokyo", priority: "low", favorite: false, notes: "Fun but book ahead." },
  { id: "", name: "Kobe day trip for Kobe beef", city: "Osaka", priority: "low", favorite: false, notes: "Short train ride from Osaka." },
] satisfies WishlistItem[]).map((w, i) => ({ ...w, id: `wishlist-${i}` }));

export const initialTransport: TransportLeg[] = ([
  { id: "", type: "flight", from: "Home", to: "Tokyo (Haneda)", date: dayDate(0), time: "14:00", duration: "—", notes: "International arrival", costJPY: 280000 },
  { id: "", type: "shinkansen", from: "Tokyo", to: "Kyoto", date: dayDate(2), time: "09:30", duration: "2h 20m", notes: "Nozomi, reserved seats", costJPY: 14000 },
  { id: "", type: "shinkansen", from: "Kyoto", to: "Osaka (via JR Special Rapid)", date: dayDate(5), time: "11:00", duration: "30m", notes: "Not JR Pass exclusive — local rapid", costJPY: 580 },
  { id: "", type: "shinkansen", from: "Osaka", to: "Tokyo", date: dayDate(8), time: "10:00", duration: "2h 30m", notes: "Nozomi, reserved seats", costJPY: 14000 },
  { id: "", type: "flight", from: "Tokyo (Haneda)", to: "Home", date: dayDate(14), time: "14:00", duration: "—", notes: "Departure flight", costJPY: 0 },
] satisfies TransportLeg[]).map((t, i) => ({ ...t, id: `transport-${i}` }));

export function buildInitialJournal(days: DayPlan[]): JournalEntry[] {
  return days.map((d) => ({
    id: `journal-${d.id}`,
    dayId: d.id,
    date: d.date,
    title: d.title,
    text: "",
    mood: "😊",
    photos: [],
  }));
}
